/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sonny
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Jugador jugador=Jugador.getJugador();
    Juego juego=Juego.getJuego();
    public Principal() {
        initComponents();
        juego.prologMysql();
        juego.cargarCombo(txtCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        txtCombo = new javax.swing.JComboBox<>();
        nuevoJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido");

        btnEstadisticas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEstadisticas.setText("Estadísticas");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        btnJugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        txtCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nuevoJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nuevoJugador.setText("Nuego jugador");
        nuevoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nuevoJugador)
                        .addGap(5, 5, 5)
                        .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(txtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
        String nombre=txtCombo.getSelectedItem().toString();
        if(!nombre.equals("")){
            jugador.setNombreJugador(nombre);
            juego.prologMysql();
            jugador.llenarDatos();
            int victorias=jugador.getVictorias();
            int derrotas=jugador.getDerrotas();
            int empates=jugador.getEmpates();
            float total=victorias+derrotas+empates;
            DecimalFormat df=new DecimalFormat("#.##%");
            String vicPor=df.format(victorias/total);
            String derPor=df.format(derrotas/total);
            String empPor=df.format(empates/total);

            Estadísticas pe=new Estadísticas();
            pe.lblNombre.setText(nombre);
            pe.lblVic.setText(""+victorias);
            pe.lblDer.setText(""+derrotas);
            pe.lblEmp.setText(""+empates);
            pe.lblTotal.setText(""+(victorias+derrotas+empates));
            pe.lblVicPor.setText(vicPor);
            pe.lblDerPor.setText(derPor);
            pe.lblEmpPor.setText(empPor);
            pe.setLocationRelativeTo(null);
            pe.setVisible(true);
            
        }else
            JOptionPane.showMessageDialog(null, "Debes de insertar un nombre válido", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        String nombre=txtCombo.getSelectedItem().toString();
            
        juego.prologMysql();
        jugador.setNombreJugador(nombre);

        jugador.llenarDatos();


        int inicio=JOptionPane.showConfirmDialog(null, "¿Deseas empezar primero?", "Nueva Partida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(inicio==JOptionPane.YES_OPTION)
            juego.setTurno("jugador");
        else
            juego.setTurno("maquina");
        juego.asignarFicha();

        Tablero t1=new Tablero();
        t1.setLocationRelativeTo(null);
        t1.setVisible(true);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void nuevoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJugadorActionPerformed
        // TODO add your handling code here:
        String nombre=JOptionPane.showInputDialog(null, "Ingresa el nombre de usuario", "Nuevo usuario", JOptionPane.QUESTION_MESSAGE);
        if(!nombre.equals("")){
            juego.baseDatosAñadir(nombre.toLowerCase().trim());
            juego.cargarCombo(txtCombo);
        }else
            JOptionPane.showMessageDialog(null, "Debes de insertar un nombre válido", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nuevoJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nuevoJugador;
    private javax.swing.JComboBox<String> txtCombo;
    // End of variables declaration//GEN-END:variables
}
